### PR TITLE
Updated readme for latest changes.

### PR DESCRIPTION
**Pull request by zerojay**

### CODE REVIEW

**Comment by XD3l** [comment]
I don't see Tiny Fugue in the installer.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
https://github.com/zerojay/RetroPie-Extra/blob/master/scriptmodules/ports/tinyfugue.sh

It's there. Perhaps you haven't copied it to the right spot or ran the install-extras script?

**Comment by robertybob** [comment]
gearboy.sh is listed twice in the Master Branch section?

**Comment by zerojay** [comment]
You're right. Thanks.

**Pull request merged**
