### PR TITLE
Minor addition to rawgl script

### PR DESCRIPTION
**Pull request by BenWlson**
I think "make clean" should be in there to ensure potential re-builds work properly. The makefile does have support for the option.

### CODE REVIEW

**Comment by zerojay** [comment]
All builds are already clean builds because of the git cloning. If you find that there are somehow issues with object files left behind, reopen this but this should not be the case at the moment.

**Comment by BenWlson** [comment]
Talking with Buzz about it earlier on IRC, the inclusion of "make clean" in the build function is due to the ability to call the build function independently via "sudo ./retropie_packages.sh rawgl build"

**Comment by zerojay** [comment]
Personally, I don't like the idea of forcing it to be cleaned. If someone wants to have it cleaned and they are building manually, they have the choice of make clean or recloning. But if it makes you feel better, here you go.

**Comment by BenWlson** [comment]
I do feel better, thanks! :-)

I know it's a trivial single line of code, but yesterday I didn't even know what it meant, and today I can now confidently say that I only sort of do.

I was just comparing scripts to existing retropie scripts and trying to learn and understand the reasons for some of the similarities and inconsistencies that I notice across them.

**Pull request merged**
