### PR TITLE
Create hurrican.sh

### PR DESCRIPTION
**Pull request by HerbFargus**
This runs fine on a pc but requires opengl unless I missed some compilation flag somewhere so it isnt really for the pi (at least in its current state)

### CODE REVIEW

**Comment by HerbFargus** [comment]
supposedly there is a build for the pi referenced here: https://retropie.org.uk/forum/topic/635/hurrican-turrican-remake/5 I tried to contact the creator for his compilation details but he said he had no time and wasnt willing to help.

**Comment by zerojay** [comment]
I think I may have it working without X now.

**Comment by XD3l** [comment]
oh... :)

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
Merging your current x86 only version to add RPi compilation steps to it shortly.

**Pull request merged**
