### PR TITLE
Move Chromium's configuration folder.

### PR DESCRIPTION
**Pull request by zerojay**

### CODE REVIEW

**Comment by XD3l** [comment]
Do think Chromium should reside in the main menu like Kodi? It seems
strange to have it listed with a bunch of game ports.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
Personally, I prefer it there than having a really bad hole in my theme on the main menu.

**Comment by XD3l** [comment]
True... that irritates me about residualvm, and residualvm don't even work
yet. I should remove it, or update the them myself.

Maybe we need a new catagory... apps?

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
Residual works fine.

**Comment by XD3l** [comment]
People stopped helping me trouble shoot it then. I tried differnt distros
of the games and all. Both Monkey Island and Grim lock at the intro movies.

“Therefore do not deceive yourself! Of all deceivers fear most yourself!”
― Søren Kierkegaard
<https://www.goodreads.com/author/show/6172.S_ren_Kierkegaard>

**Comment by zerojay** [comment]
Grim played fine for me. The intro movie was slow as hell but playing.

**Pull request merged**
