### PR TITLE
Psx2chd

### PR DESCRIPTION
**Pull request by kashaiahyah85**
I'd suggest a different branch for now, or wait. But this does work. I haven't tested rigorously.

### CODE REVIEW

**Comment by zerojay** [comment]
Please read README.md for this archive.

**Comment by kashaiahyah85** [comment]
> Please read README.md for this archive.

I did. It pointed me to another repository, which says to go back to this one. That, and the fact that there have been no updates in Years makes that seem a little silly. It doesn't matter either way to me, I just thought you might want it. It does what I need, and no hoops for Me.

**Comment by zerojay** [comment]
"Note - This repository is no longer maintained. Please feel free to fork it and take it over for the Retropie community as I am no longer using it and no longer have time to do any work with it."

**Comment by kashaiahyah85** [comment]
> "Note - This repository is no longer maintained. Please feel free to fork it and take it over for the Retropie community as I am no longer using it and no longer have time to do any work with it."

Already forked. Not sure how I'll manage to take over, given yours still appears active and simply pointing at the other. Perhaps the readme should be updated on the Other one also. Either way, I have my tools, and no interest in the broken things. Your responses of referencing yourself and then quoting yourself are a indicator that I really, really wouldn't like you. So this is where we close off. Peace.

**Comment by zerojay** [comment]
Well, when you said you read it when you clearly did not... what am I supposed to say?

Entitlement-filled comments like yours are exactly why this repository is no longer maintained. Bye.

**Pull request closed without merging**
