### PR TITLE
Add Libretro Wolfenstein3d Port

### PR DESCRIPTION
**Pull request by HerbFargus**
This works great... once. For some reason on exit it puts the framebuffer in an unuseable state, I'm pretty sure the module is done proper, but I think there is still some upstream stuff that needs to be sorted.

Note that this module is built based on the latest port changes from RetroPie.

### CODE REVIEW

**Comment by zerojay** [comment]
I'll pull this into its own branch until it's stable.

**Comment by zerojay** [comment]
I merged this into the chocolate-wolf3d branch and moved it from ports to the newly created libretrocores. I'll give this a try sometime later tonight.

**Comment by HerbFargus** [comment]
appreciated. they haven't actually done any libretro porting really so its really just wolfenstein right now,  don't know if I'll hold my breath on them porting it anytime soon, but its easier to set up than wolf4sdl with the obvious glaring issue of the jacked up framebuffer (even after using runcommand)

**Comment by zerojay** [comment]
Is it something that we can fix by simply running something like fbset -depth 32 and then fbset -depth 16 after the game closes out?

**Comment by HerbFargus** [comment]
It may be possible, I haven't looked into it too extensively tbh.

**Pull request closed without merging**
