### PR TITLE
Create lr-wolfenstein3d.sh

### PR DESCRIPTION
**Pull request by zerojay**

### CODE REVIEW

**Comment by zerojay** [comment]
@HerbFargus 

I finally took a look at this. Worked well once I understood how it worked. One problem, it creates a .chocolate_wolfenstein_3d directory for savegames in $home. When I attempted to use moveConfigDir for it, it complained about directories, etc... I don't really have the time to look into this further at the moment.

The current version of the script in the chocolate-wolf3d branch has the addition of moveConfigDir. If you can take a look at it and fix whatever is causing the issue with it, I'll probably then move it into the master branch.

**Comment by HerbFargus** [comment]
It may just be worth waiting until libretro actually ports it proper. I don't know if that will be anytime soon and we already have wolf4sdl on the main RetroPie branch so I'm happy to just let it sit til upstream sorts it.

**Comment by zerojay** [comment]
Fair enough.

**Comment by HerbFargus** [comment]
But I'll give the save settings a look if I have some free time

**Comment by zerojay** [comment]
I also noticed that they are working on an sdl 1.2x engine for libretro for some reason. Not sure how that would work but maybe it could be helpful when it gets completed.

**Pull request merged**
