### PR TITLE
add SDL Bomber (Atomic Bomberman Clone)

### PR DESCRIPTION
**Pull request by HerbFargus**

### CODE REVIEW

**Comment by zerojay** [comment]
Thanks.

**Comment by HerbFargus** [comment]
I intend on making this game a coding project to see if I can incorporate AI and other graphics. Maybe be over the course of a decade or two though...

**Comment by zerojay** [comment]
Cool, be sure to create all new audio because as it stands now... my poor ears. :P

**Comment by HerbFargus** [comment]
I'm sure that can be arranged. There are some old hidden audio bits in the original atomic bomberman laced with profanity. Might be entertaining to incorporate.

**Pull request merged**
