### PR TITLE
Update install-extras.sh

### PR DESCRIPTION
**Pull request by aikoncwd**
Compatibility with other installations that don't use "pi" as main username

### CODE REVIEW

**Comment by zerojay** [comment]
Using $HOME here will break it for everyone else.

**Comment by aikoncwd** [comment]
@zerojay Did you tried? $HOME will be "/home/pi" on regular systems, it won't break anything. Using $HOME is better because you can't ensure everybody is usong "pi" as default username. Try and test it, on my system is working well, also I troed on a regular system and is still working.

**Comment by zerojay** [comment]
Script needs to be run as root, therefore $HOME is /root.

**Comment by zerojay** [comment]
Also, I have no need to worry about what user is being used as i am supporting Retropie, not anyone's Raspbian Jessie install with who knows what changes. 

Honestly, the script is dead simple anyways. Chances are if you are running your own install like that, you know how to copy the scripts into the right place manually. The script is targeted at newbies.

I'm on the road at the moment. When i am done moving,  I'll look at this.

**Comment by zerojay** [comment]
# echo $HOME
/root

As such, I will not be merging this, sorry.

**Pull request closed without merging**
