### PR TITLE
Use working chromium deb urls

### PR DESCRIPTION
**Pull request by xurizaemon**
Also removes some commented lines from youtube-dl port.

### CODE REVIEW

**Comment by xurizaemon** [comment]
NB: I have *not* tested this PR and can't do so immediately (no retropie in the house).

I had a question I couldn't answer (#235), saw what looked like an easy fix, and went for it. Hope this is helpful!

**Comment by zerojay** [comment]
I'll likely give this a shot tonight.

**Comment by xurizaemon** [comment]
Great. Surprised I didn't say it before, but the Dropbox URLs alarmed me a bit (trust issues). These URLs might be out of date by now?

**Comment by zerojay** [comment]
It was the only option available for them at the time from what I remember.

**Pull request merged**
